# Matrix Decomposition

## Contents:
 * [Gauss Elimination](#Gauss-Elimination)
 * [Gaussian Decomposition](#Gaussian-Decomposition)
     * [$LU$](#$A-=-LU$-decomposition)
     * [$LDU$](#$A-=-LDU$-decomposition)
     * [$LDL^t$](#$A-=-LDL^t$-decomposition)
     * [$RR^t$](#$A-=-RR^t$-decomposition)
 * [Orthogonal Decomposition](#Orthogonal-Decomposition)
     * [$QR$ - Givens](#$A-=-QR$-decomposition-of-Householder)
     * [$QR$ - Householder](#$A-=-QR$-decomposition-of-Householder)
 * [Diagonal Decomposition](#Diagonal-Decomposition)
     * [$U \Sigma V^t$](#$A-=-U\Sigma-V^t$-decomposition)

#### Author:
* Sergio García Prado - [garciparedes.me](https://garciparedes.me)

In [1]:
from typing import Tuple
import enforce

In [2]:
import numpy as np

## Gauss Elimination

In [3]:
@enforce.runtime_validation
def row_reduce(A: np.ndarray, upper_reduce: bool = True) -> np.ndarray:
    A = A.astype(float)
    for i in range(A.shape[0]):
        if (A[i, i] != 0):
            for j in reversed(range(i + 1, A.shape[0])):
                A[j,:] -= A[j, i] / A[i, i] * A[i,:]    
    if upper_reduce is True:
        i = A.shape[0] - 1
        if A[i, i] != 0:
            A[i, :] = A[i, :] / A[i, i]
        for i in reversed(range(A.shape[0] - 1)):
            if (A[i, i] != 0):
                A[i, :] = A[i, :] / A[i, i]
                for j in range(i+1, A.shape[0]):
                    if(A[j, j] != 0):
                        A[i, :] -= A[i,j] / A[j, j] * A[j,:]
    return A

In [4]:
@enforce.runtime_validation
def gauss(A: np.ndarray, b: np.ndarray, generate_underdetermined:bool = True) -> np.ndarray:
    R = row_reduce(np.column_stack((A, b)))
    
    if not generate_underdetermined:
        return R[:, -1]
    else:
        # TODO(@garciparedes): Improve this code.
        i = A.shape[1] - 1
        free = 0
        while R[i, i] == 0:
            i -= 1
            free += 1

        c = np.empty([A.shape[0], free])
        for i in range(free):
            R_copy = np.copy(R)
            for j in range(free):
                R_copy[A.shape[1] - j - 1, A.shape[1] - j - 1] = 1
                R_copy[A.shape[1] - j -1 , - 1] = i + j + 1
            #print(R_copy)
            c[:, i] = row_reduce(R_copy)[:, -1]   
        return c

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.ones(3)
gauss(A, b)

array([[ 0.],
       [-1.],
       [ 1.]])

## Gaussian Decomposition

#### $A = LU$ decomposition

In [6]:
@enforce.runtime_validation
def lu(A: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    A = A.astype(np.float64)
    for i in range(A.shape[0]):
        if (A[i, i] != 0):
            for j in reversed(range(i + 1, A.shape[0])):
                A[j, (i+1):] = A[j, (i+1):] - A[j, i] / A[i, i] * A[i, (i+1):]
                A[j, i] = A[j, i] / A[i, i]
    return (np.tril(A, -1) + np.eye(A.shape[0]), np.triu(A))

In [7]:
@enforce.runtime_validation
def gauss_lu(LU: Tuple[np.ndarray, np.ndarray], b: np.ndarray) -> np.ndarray:
    for i in range(LU[0].shape[0]):
        b[i] -= np.sum(b[:i] * LU[0][i,:i])
    for i in reversed(range(LU[1].shape[0])):
        if LU[1][i][i] != 0:
            b[i] = b[i] / LU[1][i][i] - np.sum(b[(i + 1):] * LU[1][i, (i + 1):])
    return b

In [8]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

[L, U] = lu(A)

np.allclose(L @ U, A)
gauss_lu(lu(A), np.ones(3))

array([-1.,  1.,  0.])

In [9]:
L = np.array([[1, 0, 0, 0], 
              [1, 1, 0, 0],
              [2,-1, 1, 0],
              [-1,1, 0, 1]])

U = np.array([[1, 1, -1, 1], 
              [0, 1, -3, -3],
              [0, 0, 0, 0],
              [0, 0, 0, 0]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])
A = P @ L @ U
print(P @ L @ U)

[[ 1  1 -1  1]
 [ 1  2 -4 -2]
 [ 2  1  1  5]
 [-1  0 -2 -4]]


In [10]:
L = np.array([[  1,    0,   0,  0], 
              [ -1,    1,   0,  0],
              [3/2, 5/14,   1,  0],
              [  3,    0,   0,  1]])

U = np.array([[ 2,     3,   1,   2], 
              [ 0,     7,   0,   7],
              [ 0,     0,   0,-9/2],
              [ 0,     0,   0,   1]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U)

[[ 2.   3.   1.   2. ]
 [-2.   4.  -1.   5. ]
 [ 3.   7.   1.5  1. ]
 [ 6.   9.   3.   7. ]]


In [11]:
L = np.array([[  1,   0,   0], 
              [3/4,   1,   0],
              [-1/2,  0,   1]])

U = np.array([[ 4,    2,   6], 
              [ 0, -3/2, 5/2],
              [ 0,     0, 0]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ L @ U)

[[ 4.  2.  6.]
 [ 3.  0.  7.]
 [-2. -1. -3.]]


In [12]:
L = np.array([[  1,    0,   0,  0], 
              [1/2,   1,   0,  0],
              [  1,   -1,   1,  0],
              [3/2,   -1, 4/3,  1]])

U = np.array([[ 2,  0,   1,   2], 
              [ 0,  1,-1/2,   1],
              [ 0,  0, 3/2,   0],
              [ 0,  0,   0,   1]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U)

[[ 2.  0.  1.  2.]
 [ 1.  1.  0.  2.]
 [ 2. -1.  3.  1.]
 [ 3. -1.  4.  3.]]


In [13]:
L = np.array([[1, 0, 0, 0], 
              [-1, 1, 0, 0],
              [3, 1/2, 1, 0],
              [2, 0, 0, 1]])

U = np.array([[1, 2, 0, -2], 
              [0, 2, 4, 5],
              [0, 0, 0, 1/2],
              [0, 0, 0, 1]])

P = np.array([[1, 0, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0],
              [0, 1, 0, 0]])

print(P @ L @ U)

[[ 1.  2.  0. -2.]
 [ 2.  4.  0. -3.]
 [ 3.  7.  2. -3.]
 [-1.  0.  4.  7.]]


## Gaussian Decomposition

#### $A = LDU$ decomposition

In [14]:
@enforce.runtime_validation
def ldu(A: np.ndarray) -> Tuple[np.array, np.array, np.array]:
    L = np.zeros(A.shape)
    D = np.zeros(A.shape)
    U = np.zeros(A.shape)
    
    raise NotImplementedError("TODO IMPLEMENT YET: LDU")

In [15]:
L = np.array([[  1,   0,   0], 
              [  5,   1,   0],
              [ -2,   3,   1]])

U = np.array([[  4,  -2,   1], 
               [ 0,   3,   7],
               [ 0,   0,  -2]])

D = np.array([[ 4, 0, 0], 
              [0, 3, 0],
              [0, 0,-2]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ L @ U)

[[ 4 -2  1]
 [20 -7 12]
 [-8 13 17]]


In [16]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [6, 8, 1, 0],
              [5, -5, 0, 1]])

U = np.array([[1, 2, -2, 1],
              [0, -3, 1, 2],
              [0, 0, -2, 0],
              [0, 0, 0, 8]])

D = np.array([[1, 0, 0, 0],
              [0, -3, 0, 0],
              [0, 0, -2, 0],
              [0, 0, 0, 8]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U)

[[  1   2  -2   1]
 [  4   5  -7   6]
 [  6 -12  -6  22]
 [  5  25 -15   3]]


In [17]:
L = np.array([[  1,   0,   0], 
              [  5,   1,   0],
              [ -2,   3,   1]])

D = np.array([[ 4, 0, 0], 
              [0, 3, 0],
              [0, 0,-2]])

U = np.array([[ 1,-1/2,1/4], 
               [ 0,   1,7/3],
               [ 0,   0,  1]])


P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ L @ D @ U)

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 17.]]


In [18]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [6, 8, 1, 0],
              [5, -5, 0, 1]])

D = np.array([[1, 0, 0, 0],
              [0, -3, 0, 0],
              [0, 0, -2, 0],
              [0, 0, 0, 8]])

U = np.array([[1, 2, -2, 1],
               [0, 1, -1/3, -2/3],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])


P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ D @ U)

[[  1.   2.  -2.   1.]
 [  4.   5.  -7.   6.]
 [  6. -12.  -6.  22.]
 [  5.  25. -15.   3.]]


In [19]:
L = np.array([[1, 0, 0, 0, 0], 
              [0, 1, 0, 0, 0],
              [4, 2, 1, 0, 0],
              [5, 3, -1, 1, 0],
              [0, 0, 0, 0, 1]])

U = np.array([[1, 2, -2, 1, 1],
              [0, 1, -1/3, -2/3, -2/3],
              [0, 0, 1, 0, -1/2],
              [0, 0, 0, 1, 1/2],
              [0, 0, 0, 0, 1]])

D = np.array([[1, 0, 0, 0, 0],
              [0, -3, 0, 0, 0],
              [0, 0, -2, 0, 0],
              [0, 0, 0, 2, 0],
              [0, 0, 0, 0, 2]])

P = np.array([[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 1]])

print(P @ L @ D @ U)

[[ 1.  2. -2.  1.  1.]
 [ 0. -3.  1.  2.  2.]
 [ 4.  2. -8.  8.  9.]
 [ 5.  1. -5. 13. 11.]
 [ 0.  0.  0.  0.  2.]]


#### $A = LDL^t$ decomposition

In [20]:
@enforce.runtime_validation
def ldl(A: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    L = np.zeros(A.shape)
    D = np.zeros(A.shape)
    
    raise NotImplementedError("TODO IMPLEMENT YET LDL")

In [21]:
L = np.array([[1, 0, 0], 
              [-1/2, 1, 0],
              [-2, -9/8, 1]])

D = np.array([[4, 0, 0], 
              [0, -8, 0],
              [0, 0, 89/8]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[ 4. -2. -8.]
 [-2. -7. 13.]
 [-8. 13. 17.]]


In [22]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [-2, 4/11, 1, 0],
              [1, -21/11, 227/94, 1]])

D = np.array([[1, 0, 0, 0], 
              [0, -11, 0, 0],
              [0, 0, -94/11, 0],
              [0, 0, 0, 8077/94]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[  1.   4.  -2.   1.]
 [  4.   5. -12.  25.]
 [ -2. -12.  -6. -15.]
 [  1.  25. -15.  -3.]]


In [23]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [-2, 4/11, 1, 0],
              [1, -21/11, 227/94, 1]])

D = np.array([[1, 0, 0, 0], 
              [0, -11, 0, 0],
              [0, 0, -94/11, 0],
              [0, 0, 0, 8077/94]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[  1.   4.  -2.   1.]
 [  4.   5. -12.  25.]
 [ -2. -12.  -6. -15.]
 [  1.  25. -15.  -3.]]


In [24]:
L = np.array([[1, 0, 0, 0, 0], 
              [2, 1, 0, 0, 0],
              [4, 6/7, 1, 0, 0],
              [5, 8/7, 127/132, 1, 0],
              [1, 0, -35/132, -1163/739, 1]])

D = np.array([[1, 0, 0, 0, 0], 
              [0, -7, 0, 0, 0],
              [0, 0, -132/7, 0, 0],
              [0, 0, 0, 739/132, 0],
              [0, 0, 0, 0,  -8528/739]])

P = np.array([[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[ 1.  2.  4.  5.  1.]
 [ 2. -3.  2.  2.  2.]
 [ 4.  2. -8. -5.  9.]
 [ 5.  2. -5.  4.  1.]
 [ 1.  2.  9.  1.  2.]]


## $A = RR^t$ decomposition

In [25]:
@enforce.runtime_validation
def rr(A: np.ndarray) -> Tuple[np.ndarray]:
    R = np.zeros(A.shape)
    
    raise NotImplementedError("TODO IMPLEMENT YET: RR")

In [26]:
R = np.array([[2, 0, 0],
              [1, 3, 0],
              [-2, 2, 1]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ R @ np.transpose(R))

[[ 4  2 -4]
 [ 2 10  4]
 [-4  4  9]]


In [27]:
R = np.array([[2, 0, 0],
              [1, np.sqrt(8), 0],
              [0, np.sqrt(8) / 2, np.sqrt(3)]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ R @ np.transpose(R))

[[4. 2. 0.]
 [2. 9. 4.]
 [0. 4. 5.]]


## Orthogonal Decomposition

#### $A = QR$ decomposition of Gram Schmidt

In [28]:
def inner_product(v1, v2):
    return np.sum(v1 * v2)

In [29]:
def norm_2(v):
    return np.sqrt(inner_product(v, v))

In [30]:
def normalize(v):
    return v / norm_2(v)

In [31]:
def gram_schmidt(V):
    Q = np.zeros(V.shape)
    for i in range(Q.shape[1]):
        Q[:, i] = V[:, i] 
        for j in range(i):
            Q[:, i] -= inner_product(Q[:, j], Q[:, i]) * Q[:, j]
        Q[:, i] = normalize(Q[:, i]) 
    return Q

#### $A = QR$ decomposition of Givens 

In [32]:
@enforce.runtime_validation
def rotator(A: np.ndarray, i: int, j: int, k: int) -> np.ndarray:
    G = np.eye(A.shape[0])
    r = np.sqrt(A[i, k] ** 2 + A[j, k] ** 2)
    if A[j, k] != 0:
        G[i, i] = A[i, k] / r
        G[i, j] = A[j, k] / r
        G[j, i] = - A[j, k] / r
        G[j, j] = A[i, k] / r
    return G

In [33]:
@enforce.runtime_validation
def qr_givens(A: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    Q = np.eye(A.shape[0])
    for j in range(A.shape[1]):
        G = np.eye(A.shape[0])
        for i in reversed(range(j, A.shape[1])):
            G = rotator(G @ A, i, i + 1, j) @ G
        Q = Q @ np.transpose(G)
        A = G @ A
    return (Q, A)

In [34]:
A = np.array([[1,-1,1],
              [1,1,1],
              [1,1,-1],
             [1,1,1]])

b = np.array([1, 1, -1, 0])
[Q, R] = qr_givens(A)
c = (np.transpose(Q) @ b).flatten()
x = np.linalg.solve(R[0:R.shape[1], :], c[0:R.shape[1]])

print("A =", np.round(A, decimals=2),  '\n', sep='\n')
print("Q =", np.round(Q, decimals=2),  '\n', sep='\n')
print("R =", np.round(R, decimals=2),  '\n', sep='\n')
print("Q @ R =", np.round(Q @ R, decimals=2), '\n', sep='\n')
print("b =", np.round(b, decimals=2), '\n', sep='\n')
print("c =", np.round(c, decimals=2), '\n', sep='\n')
print("x =", np.round(x, decimals=2), '\n', sep='\n')

A =
[[ 1 -1  1]
 [ 1  1  1]
 [ 1  1 -1]
 [ 1  1  1]]


Q =
[[ 0.5  -0.87  0.    0.  ]
 [ 0.5   0.29  0.41  0.71]
 [ 0.5   0.29 -0.82  0.  ]
 [ 0.5   0.29  0.41 -0.71]]


R =
[[ 2.    1.    1.  ]
 [ 0.    1.73 -0.58]
 [ 0.    0.    1.63]
 [ 0.    0.    0.  ]]


Q @ R =
[[ 1. -1.  1.]
 [ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 1.  1.  1.]]


b =
[ 1  1 -1  0]


c =
[ 0.5  -0.87  1.22  0.71]


x =
[ 0.   -0.25  0.75]




#### $A = QR$ decomposition of Householder

In [35]:
@enforce.runtime_validation
def reflector(A: np.ndarray, i: int) -> np.ndarray:
    x = np.take(A, [i], 1)
    y =  np.concatenate([x[:i], [[np.sqrt(np.sum(np.power(x[i:],2)))]],
                        np.zeros([A.shape[0] - i - 1, 1])])
    u = (x - y)
    return np.eye(A.shape[0]) - (2 / np.squeeze(u.T @ u)) * (u @ u.T)

In [36]:
@enforce.runtime_validation
def qr_householder(A: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    Q = np.eye(A.shape[0])
    for i in range(A.shape[1]):
        R = reflector(A, i)
        Q = Q @ R
        A = R @ A
    return (Q, A)

In [37]:
A = np.array([[1,-1,1],
                [1,1,1],
                [1,1,-1],
                [1,1,1]])

b = np.array([1, 1, -1, 0])

[Q, R] = qr_householder(A)
c = (np.transpose(Q) @ b).flatten()
x = np.linalg.solve(R[0:R.shape[1], :], c[0:R.shape[1]])

print("A =", np.round(A, decimals=2),  '\n', sep='\n')
print("Q =", np.round(Q, decimals=2),  '\n', sep='\n')
print("R =", np.round(R, decimals=2),  '\n', sep='\n')
print("Q @ R =", np.round(Q @ R, decimals=2), '\n', sep='\n')
print("b =", np.round(b, decimals=2), '\n', sep='\n')
print("c =", np.round(c, decimals=2), '\n', sep='\n')
print("x =", np.round(x, decimals=2), '\n', sep='\n')

A =
[[ 1 -1  1]
 [ 1  1  1]
 [ 1  1 -1]
 [ 1  1  1]]


Q =
[[ 0.5  -0.87  0.   -0.  ]
 [ 0.5   0.29  0.41 -0.71]
 [ 0.5   0.29 -0.82  0.  ]
 [ 0.5   0.29  0.41  0.71]]


R =
[[ 2.    1.    1.  ]
 [ 0.    1.73 -0.58]
 [ 0.   -0.    1.63]
 [ 0.    0.    0.  ]]


Q @ R =
[[ 1. -1.  1.]
 [ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 1.  1.  1.]]


b =
[ 1  1 -1  0]


c =
[ 0.5  -0.87  1.22 -0.71]


x =
[ 0.   -0.25  0.75]




## Diagonal Decomposition

#### $A = U\Sigma V^t$ decomposition

In [38]:
def eig_vals(A):
    # TODO(@garciparedes): Replace rounding with appropriate approach
    return np.round(np.linalg.eigvals(A), decimals = 4)

In [39]:
@enforce.runtime_validation
def usv(A: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    A1 = A.T @ A
    A2 = A @ A.T
    
    lambdas = np.sort(eig_vals(A1))

    S = np.diag(np.sqrt(lambdas))
    
    V = np.empty((A1.shape[1], 0), np.float64)
    for l in np.sort(np.unique(lambdas)):
        V = np.append(V, gauss(A1 - l * np.eye(A1.shape[0]), np.zeros(A1.shape[0])), axis=1)
    V = gram_schmidt(V)

    U = np.empty((A2.shape[1], 0), float)
    for (i, l) in enumerate(lambdas):
        if l == 0:
            U = np.append(U, gram_schmidt(gauss(A2, np.zeros(A2.shape[0]))), axis=1)
        else:
            U = np.append(U, 1 / np.sqrt(l) * A @ V[:, i, None], axis=1)
            
    return (U, S, V)

In [40]:
A = np.array([[1, -1, 2],
              [1, 2, -1],
              [2, 1, 1]])

[U, S, V]  = usv(A)

np.allclose(U @ S @ V.T, A)

True