In [1]:
import numpy as np

## A = LU decomposition

In [2]:
L = np.array([[1, 0, 0, 0], 
              [1, 1, 0, 0],
              [2,-1, 1, 0],
              [-1,1, 0, 1]])

U = np.array([[1, 1, -1, 1], 
              [0, 1, -3, -3],
              [0, 0, 0, 0],
              [0, 0, 0, 0]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U)

[[ 1  1 -1  1]
 [ 1  2 -4 -2]
 [ 2  1  1  5]
 [-1  0 -2 -4]]


In [3]:
L = np.array([[  1,    0,   0,  0], 
              [ -1,    1,   0,  0],
              [3/2, 5/14,   1,  0],
              [  3,    0,   0,  1]])

U = np.array([[ 2,     3,   1,   2], 
              [ 0,     7,   0,   7],
              [ 0,     0,   0,-9/2],
              [ 0,     0,   0,   1]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U)

[[ 2.   3.   1.   2. ]
 [-2.   4.  -1.   5. ]
 [ 3.   7.   1.5  1. ]
 [ 6.   9.   3.   7. ]]


In [4]:
L = np.array([[  1,   0,   0], 
              [3/4,   1,   0],
              [-1/2,  0,   1]])

U = np.array([[ 4,    2,   6], 
              [ 0, -3/2, 5/2],
              [ 0,     0, 0]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

P @ L @ U @ np.linalg.inv(P)

array([[ 4.,  2.,  6.],
       [ 3.,  0.,  7.],
       [-2., -1., -3.]])

In [5]:
L = np.array([[  1,    0,   0,  0], 
              [1/2,   1,   0,  0],
              [  1,   -1,   1,  0],
              [3/2,   -1, 4/3,  1]])

U = np.array([[ 2,  0,   1,   2], 
              [ 0,  1,-1/2,   1],
              [ 0,  0, 3/2,   0],
              [ 0,  0,   0,   1]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U)

[[ 2.  0.  1.  2.]
 [ 1.  1.  0.  2.]
 [ 2. -1.  3.  1.]
 [ 3. -1.  4.  3.]]


## A = LDU decomposition

In [6]:
L = np.array([[  1,   0,   0], 
              [  5,   1,   0],
              [ -2,   3,   1]])

U1 = np.array([[  4,  -2,   1], 
               [ 0,   3,   7],
               [ 0,   0,  -2]])

D = np.array([[ 4, 0, 0], 
              [0, 3, 0],
              [0, 0,-2]])

U2 = np.array([[ 1,-1/2,1/4], 
               [ 0,   1,7/3],
               [ 0,   0,  1]])


P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ L @ U1)
print(P @ L @ D @ U2)

[[ 4 -2  1]
 [20 -7 12]
 [-8 13 17]]
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 17.]]


In [7]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [6, 8, 1, 0],
              [5, -5, 0, 1]])

U1 = np.array([[1, 2, -2, 1],
              [0, -3, 1, 2],
              [0, 0, -2, 0],
              [0, 0, 0, 8]])

D = np.array([[1, 0, 0, 0],
              [0, -3, 0, 0],
              [0, 0, -2, 0],
              [0, 0, 0, 8]])

U2 = np.array([[1, 2, -2, 1],
               [0, 1, -1/3, -2/3],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])


P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ U1)
print(P @ L @ D @ U2)

[[  1   2  -2   1]
 [  4   5  -7   6]
 [  6 -12  -6  22]
 [  5  25 -15   3]]
[[  1.   2.  -2.   1.]
 [  4.   5.  -7.   6.]
 [  6. -12.  -6.  22.]
 [  5.  25. -15.   3.]]


In [8]:
L = np.array([[1, 0, 0, 0, 0], 
              [0, 1, 0, 0, 0],
              [4, 2, 1, 0, 0],
              [5, 3, -1, 1, 0],
              [0, 0, 0, 0, 1]])

U = np.array([[1, 2, -2, 1, 1],
              [0, 1, -1/3, -2/3, -2/3],
              [0, 0, 1, 0, -1/2],
              [0, 0, 0, 1, 1/2],
              [0, 0, 0, 0, 1]])

D = np.array([[1, 0, 0, 0, 0],
              [0, -3, 0, 0, 0],
              [0, 0, -2, 0, 0],
              [0, 0, 0, 2, 0],
              [0, 0, 0, 0, 2]])

P = np.array([[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 1]])

print(P @ L @ D @ U)

[[ 1.  2. -2.  1.  1.]
 [ 0. -3.  1.  2.  2.]
 [ 4.  2. -8.  8.  9.]
 [ 5.  1. -5. 13. 11.]
 [ 0.  0.  0.  0.  2.]]


## A = LDt(L) decomposition

In [9]:
L = np.array([[1, 0, 0], 
              [-1/2, 1, 0],
              [-2, -9/8, 1]])

D = np.array([[4, 0, 0], 
              [0, -8, 0],
              [0, 0, 89/8]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[ 4. -2. -8.]
 [-2. -7. 13.]
 [-8. 13. 17.]]


In [10]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [-2, 4/11, 1, 0],
              [1, -21/11, 227/94, 1]])

D = np.array([[1, 0, 0, 0], 
              [0, -11, 0, 0],
              [0, 0, -94/11, 0],
              [0, 0, 0, 8077/94]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[  1.   4.  -2.   1.]
 [  4.   5. -12.  25.]
 [ -2. -12.  -6. -15.]
 [  1.  25. -15.  -3.]]


In [11]:
L = np.array([[1, 0, 0, 0], 
              [4, 1, 0, 0],
              [-2, 4/11, 1, 0],
              [1, -21/11, 227/94, 1]])

D = np.array([[1, 0, 0, 0], 
              [0, -11, 0, 0],
              [0, 0, -94/11, 0],
              [0, 0, 0, 8077/94]])

P = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[  1.   4.  -2.   1.]
 [  4.   5. -12.  25.]
 [ -2. -12.  -6. -15.]
 [  1.  25. -15.  -3.]]


In [12]:
L = np.array([[1, 0, 0, 0, 0], 
              [2, 1, 0, 0, 0],
              [4, 6/7, 1, 0, 0],
              [5, 8/7, 127/132, 1, 0],
              [1, 0, -35/132, -1163/739, 1]])

D = np.array([[1, 0, 0, 0, 0], 
              [0, -7, 0, 0, 0],
              [0, 0, -132/7, 0, 0],
              [0, 0, 0, 739/132, 0],
              [0, 0, 0, 0,  -8528/739]])

P = np.array([[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 1]])

print(P @ L @ D @ np.transpose(L))

[[ 1.  2.  4.  5.  1.]
 [ 2. -3.  2.  2.  2.]
 [ 4.  2. -8. -5.  9.]
 [ 5.  2. -5.  4.  1.]
 [ 1.  2.  9.  1.  2.]]


## A = Rt(R) decomposition

In [13]:
R = np.array([[2, 0, 0],
              [1, 3, 0],
              [-2, 2, 1]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ R @ np.transpose(R))

[[ 4  2 -4]
 [ 2 10  4]
 [-4  4  9]]


In [14]:
R = np.array([[2, 0, 0],
              [1, np.sqrt(8), 0],
              [0, np.sqrt(8) / 2, np.sqrt(3)]])

P = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

print(P @ R @ np.transpose(R))

[[4. 2. 0.]
 [2. 9. 4.]
 [0. 4. 5.]]
